---

- name: APT - Install
  apt:
    pkg:
      - sudo
      - build-essential
      - qemu-guest-agent
      - automake
      - dkms
      - vim
      - vagrant-sshfs
      - vagrant-cachier
      - cloud-init
      - curl
      - wget
      - file
      - wish
      - tcl
      - openssl
      - gnupg
      - git
      - screen
      - direnv
      - jq
      - pandoc
      - texlive
      - python3
      - python3-dev
      - python3-pip
      - libssl-dev
      - libffi-dev
      - libproj-dev
      - libcap-dev
      - proj-bin
      - ebtables
      - bzip2
      - libev-dev
      - ca-certificates
      - lsb-release
      - libtool
      - gawk
      - libreadline-dev
      - ufw
      - wireshark
      - hping3
      - iputils-arping
      - nmap
      - telnet
      - socat
      - tcpdump
      - tcpflow
      - thunderbird
      - swaks
      - ftp
      - whois
      - dnstracer
      - dnsutils
      - htop
      - iperf3
      - mtr
      - traceroute
      - netcat
      - ncat
      - wait-for-it
      - ethtool
    update_cache: yes
    install_recommends: no