---

- name: CORE - Install pip dependencies
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - invoke
    - poetry
    - grpcio-tools

- name: CORE - Update alternatives ebtables
  become: true
  ansible.builtin.shell: update-alternatives --set ebtables /usr/sbin/ebtables-legacy

- name: OSPF MDR - Checkout
  ansible.builtin.git:
    repo: https://github.com/USNavalResearchLaboratory/ospf-mdr.git
    dest: /opt/ospf-mdr
    version: f21688cdcac30fb10b1ebac0063eb24e4583e9b4
    force: true

- name: OSPF MDR - Patch
  lineinfile:
    dest: /opt/ospf-mdr/lib/built.h
    state: present
    regexp: '^const char \*quagga_built_string;'
    line: 'extern const char *quagga_built_string;'

- name: OSPF MDR - Bootstrap
  ansible.builtin.shell: ./bootstrap.sh
  args:
    chdir: /opt/ospf-mdr

- name: OSPF MDR - Configure
  ansible.builtin.shell: |
    ./configure \
      --disable-doc \
      --enable-user=root \
      --enable-group=root \
      --with-cflags=-ggdb \
      --sysconfdir=/usr/local/etc/quagga \
      --enable-vtysh \
      --localstatedir=/var/run/quagga
  args:
    chdir: /opt/ospf-mdr

- name: OSPF MDR - make
  make:
    chdir: /opt/ospf-mdr
    params:
      NUM_THREADS: 2

- name: OSPF MDR - make install
  make:
    chdir: /opt/ospf-mdr
    target: install

- name: CORE - Git checkout
  ansible.builtin.git:
    repo: https://github.com/coreemu/core.git
    dest: /opt/core
    version: release-8.0.0
    force: true

- name: CORE - Invoke install
  ansible.builtin.shell: inv install -i debian
  args:
    chdir: /opt/core

- name: CORE - Invoke install
  file:
    src: /usr/local/bin/core-gui-legacy
    dest: /bin/core-gui
    state: link

- name: CORE - Enable
  systemd:
    name: core-daemon
    state: started
    enabled: yes
    masked: no