---

- name: WIRESHARK - Install
  apt:
    name: wireshark
    update_cache: yes
    install_recommends: no

- name: WIRESHARK - No root to capture
  ansible.builtin.shell: |
    addgroup -system wireshark
    chown root:wireshark /usr/bin/dumpcap
    setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap