---

- name: Provision
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Install a list of packages
    become: true
    apt:
      pkg:
        - sudo
        - build-essential
        - qemu-guest-agent
        - automake
        - dkms
        - vim
        - vagrant-sshfs
        - vagrant-cachier
        - cloud-init
        - curl
        - wget
        - file
        - wish
        - tcl
        - openssl
        - gnupg
        - git
        - screen
        - direnv
        - jq
        - pandoc
        - texlive
        - python3
        - python3-dev
        - python3-pip
        - libssl-dev
        - libffi-dev
        - libproj-dev
        - libcap-dev
        - proj-bin
        - ebtables
        - bzip2
        - libev-dev
        - ca-certificates
        - lsb-release
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - libtool
        - gawk
        - libreadline-dev
        - ufw
      update_cache: yes
      install_recommends: no

  - name: Allow 'sudo' group to have passwordless sudo
    become: true
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Permit Root Login
    become: true
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^#PermitRootLogin prohibit-password'
      line: 'PermitRootLogin yes'

  - name: Install pip dependencies
    become: true
    pip:
      name: "{{ item }}"
      executable: pip3
    loop:
    - docker[tls]==5.0.3
    - docker-compose==1.29.2

  - name: UFW - Allow forwarding
    become: true
    lineinfile:
      dest: /etc/default/ufw
      state: present
      regexp: '^DEFAULT_FORWARD_POLICY="DROP"'
      line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

  - name: Politica de entrada permisiva
    community.general.ufw:
      state: enabled
      direction: incoming
      policy: allow

  - name: UFW - systemd enabled on boot
    become: true
    ansible.builtin.systemd:
      name: ufw
      state: started
      enabled: yes